### ISSUE TITLE
Cannot read Keyed items beginning with 'F'

### ISSUE THREAD

**Issue by lukeplausin** [aws/aws-iot-device-sdk-arduino-yun#11]
Hi All,

I have noticed there is a bug whereby you can't access key/value pairs when the value begins with an uppercase F.

Shadow state
{"state":{"desired":{"text":"Foxtrot"}}}
myClient.getDeltaValueByKey("JSON-0", "text", buffer, 32);
buffer = '0\'

Shadow state
{"state":{"desired":{"text":"Golf"}}}
myClient.getDeltaValueByKey("JSON-0", "text", buffer, 32);
buffer = "Golf"

**Comment by liuszeng** [comment]
Hi @lukeplausin ,

Thank you for using the AWS IoT Arduino Yun SDK! This is indeed a bug in JSON key/value pair retrieving process. We'll look into fixing this and incorporate it in the next release.

Thanks,
Liusu

**Comment by liuszeng** [comment]
Fixed in release [v2.1.1](https://github.com/aws/aws-iot-device-sdk-arduino-yun/releases/tag/v2.1.1).
