### ISSUE TITLE
Arduino Uno + Ethernet Shield

### ISSUE THREAD

**Issue by Piero87** [aws/aws-iot-device-sdk-arduino-yun#12]
Hi, can I use Arduino Uno + Ethernet Shield?
Or there is something library that can I use with that configuration?

If I can't I want also know if I can use Arduino Uno + Ethernet Shield with one of the MQTT library available open source for Arduino without certificate, so disable certificate for my thing on AWS IOT.

Thanks

**Comment by liuszeng** [comment]
Hi @Piero87 ,

Thank you very much for your interest in AWS IoT!

Unfortunately, you cannot use AWS IoT Arduino Yun SDK on Arduino Uno + Ethernet Shield. The AWS IoT Arduino Yun SDK is built on top of the dual-processor architecture specifically for Arduino Yun and its compatible boards. It transmits commands over the Serial1 bridge in between and relies on the more powerful AR9331 chip to do all the heavy lifting for secured MQTT operations.

Customer security is always a big focus for AWS IoT. As is mentioned in our [developer's guide](http://docs.aws.amazon.com/iot/latest/developerguide/iot-security-identity.html), the security model is one of shared responsibility, with an emphasis on security in the cloud. Each connected device needs a credential to access the message broker or the Thing Shadows service. Under the consideration of customer security, connecting without proper authentication process/disabling authentication are not allowed and will result in handshake error.

Thanks,
Liusu

**Comment by diegommarino** [comment]
Are there any strategy to connect a Arduino UNO or the ESP8266 module with AWS IoT? If not, do you have plans to create a SDK for working with a single processor architecture?

**Comment by dnavarrom** [comment]
try this https://github.com/dnavarrom/aws_mqtt_arduino_uno
