### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by lukeplausin** [aws/aws-iot-device-sdk-arduino-yun#13]
Hi All,

Thanks for all your great work on the aws yun SDK. It's been fun working with it so far!

I would like to make some suggestions about reducing the memory footprint of the MQTT driver. At the moment the example with shadow states takes up 75% of the memory on the ATmega. This leaves little room for other things to run alongside.

I have some suggestions which I would like to make sincerely. I know the driver is a work in progress, so maybe this is already planned.

1: I noticed there are a lot of string literals in aws_iot_mqtt.cpp - these are stored in SRAM when they could be offloaded to the flash. EG:
Instead of: sprintf(rw_buf, "state\"reported\"%s\n", key);
Use: sprintf_P(rw_buf, PSTR("state\"reported\"%s\n"), key);

2: The keyed functions will clear the data in the buffer if the value isn't returned correctly. This means I need to use an intermediate buffer and check the error code before copying again. This is a waste of resources, and could be avoided if the client left the target buffers alone on error

Now I have:
if(myClient.getDeltaValueByKey("JSON-0", "text", buffer, 32) == ERROR_NONE)
{ strcpy(theData, buffer); }

Better:
myClient.getDeltaValueByKey("JSON-0", "text", theData, THE_DATA_SIZE) 
// I cant do this because myClient clears theData if the result is not ERROR_NONE

3: I still have to construct the return messages on the ATmega, to report the state back up to AWS. This means I need a huge buffer to hold a JSON document. It would be better to have some kind of function similar to the getValueByKey to construct a JSON doc on the linux host.

eg:
myClient.setValueByKey("JSON-R", "state\"reported\"text", theData)
myClient.sendMessage("JSON-R");

Thanks!

**Comment by liuszeng** [comment]
Hi @lukeplausin ,

Thank you very much for all your inputs on the AWS IoT Arduino Yun SDK. Memory optimization and JSON processing are definitely within our roadmap. We will put these in our backlog and prioritize them against other tasks. We will incorporate these changes into future releases.

Thanks,
Liusu

**Comment by zeemy23** [comment]
+1!

**Comment by liuszeng** [comment]
Improved memory usage in release v2.2.0.

**Comment by hedeshianaws** [comment]
Fix was released in Jul 2016
