### ISSUE TITLE
Feature Request: Allow use of SoftwareSerial

### ISSUE THREAD

**Issue by pherris** [aws/aws-iot-device-sdk-arduino-yun#15]
Hey guys, thanks for the library. 

I was hacking on getting the library running on the Dragino and Arduino Uno but ran into the issue where the `Serial1` port was not available as the Uno has only one Serial port. 

It seems like it should be possible to run with an Uno if we could configure [SoftwareSerial](https://www.arduino.cc/en/Tutorial/SoftwareSerialExample) and use some of the other Arduino digital pins for the second Serial port.  However, this library has hardcoded the use of `Serial1` (seems to be exclusively in [aws_iot_mqtt.cpp](https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Arduino-Yun-Library/aws_iot_mqtt.cpp)) for communication to the Dragino.

If we could set some config values for `SoftwareSerial` in the config of our sketch (like we do for `AWS_IOT_CLIENT_ID`), it seems like it would be straight forward to make this library work with much more hardware. I know we can solve this with different hardware, but it'd be great to have this software solution as well.

Thanks!

**Comment by pwdel** [comment]
I second this request.

**Comment by liuszeng** [comment]
Hi @pherris ,

Thank you very much for your interest in AWS IoT Arduino Yun SDK!

The AWS IoT Arduino Yun SDK is specifically designed for Arduino Yun and its compatible board, which has a dual-processor architecture and uses Serial1 (hard wired on Arduino Yun) for communication between ATmega32u4 and AR9331. This is why Serial1 is hardcoded in the SDK to provide a 'tunnel' for communication between the two chips.

Dragino has provided a Yun Shield to add extra internet connectivity ability to Arduino boards. Here is a [AWS IoT forum post](https://forums.aws.amazon.com/thread.jspa?messageID=706691&#706691) about using the AWS IoT Arduino Yun SDK on Arduino Due + Yun Shield. Although it is hardware solution, you can take a look and try it as a work-around for now.

We appreciate your input on the SDK to make it better and compatible for more hardware platforms. We will put the request in our backlog and prioritize them against other tasks and incorporate the changes into future releases.

Thanks,
Liusu
