### ISSUE TITLE
Support for ESP8266 and Arduino ?

### ISSUE THREAD

**Issue by sabas1080** [aws/aws-iot-device-sdk-arduino-yun#2]
Hi

Will support for Arduino UNO ESP8266 or Wi-Fi ?

Thanks

**Comment by synaptic-axon** [comment]
I've been working on integrating this with the ESP8266 as well.

**Comment by sabas1080** [comment]
Excelente, Is there a repository?

**Comment by liuszeng** [comment]
Hi @sabas1080: 

We are currently only supporting the Arduino Yun architecture.

The AWS IoT device SDK needs an existing TCP/IP stack, TLS implementation and crypto library. The C-SDK (aws-iot-device-sdk-embedded-C) shows how to modify the C-SDK to run on either mbedTLS or openSSL. The implementation of TLS1.2 with mutual authentication using client certificates (as used by AWS IoT platform) requires a certain amount of memory that only few Arduinos meet.

The Arduino Yun features a 2 processor architecture where only the application sketch runs on the smaller ATmega processor while TLS, MQTT and crypto tasks are offloaded to the large controller. Thereby the Arduino Yun SDK is very specific for this particular board. 

We have not come across a working and security tested implementation of TLS1.2 (supporting the required cipher suites and mutual authentication) on ESP8266 and hence don't support it yet. 

We are sorry for not being able to provide a more positive answer at the moment and we will continue to look into the developments happening around the ESP8266.

Thanks,
AWS IoT SDK Team

**Comment by liuszeng** [comment]
Hi @sabas1080 ,

We haven't heard back from you on this issue and hope that we were able to answer your question. 
We're going to close this issue for now. If you'd like to ask further questions on this topic, please feel free to re-open it.

Thanks,
AWS IoT SDK Team

**Comment by diegommarino** [comment]
Do you had any improvement in integrating the SDK with ESP8266?
