### ISSUE TITLE
basic PubSub Error connect failed -1

### ISSUE THREAD

**Issue by Daniel-Git-Hub** [aws/aws-iot-device-sdk-arduino-yun#24]
config is as follows
AWS_IOT_MQTT_HOST "**************.iot.ap-northeast-1.amazonaws.com"
# define AWS_IOT_MQTT_PORT 8883                                  // your port
# define AWS_IOT_CLIENT_ID   "seeeduino"                     // your client ID
# define AWS_IOT_MY_THING_NAME "seeeduino"                       // your thing name
# define AWS_IOT_ROOT_CA_FILENAME "rootCA.pem"           // your root-CA filename
# define AWS_IOT_CERTIFICATE_FILENAME "certificate.pem.crt"                 // your certificate filename
# define AWS_IOT_PRIVATE_KEY_FILENAME "private.pem.key"              // your private key filename

**Comment by liuszeng** [comment]
Hi @Daniel-Git-Hub ,

Thank you very much for using AWS IoT Arduino Yun SDK!

As the initial debugging step, can you go ahead and verify the integrity of your connectivity information and credentials using another MQTT client, e.g., [MQTT.fx](http://mqttfx.jfx4ee.org/), and see if you can connect?

Please let us know how it goes.

Thanks,
Liusu

**Comment by Daniel-Git-Hub** [comment]
thanks yes I can connect to that.
But I fully reset it (using a seeduino) and then re uploaded everything and set it up again
and I could connect using the default MQTT client
