### ISSUE TITLE
Can I use AWS IoT and use the bridge?

### ISSUE THREAD

**Issue by GabrielFiletti** [aws/aws-iot-device-sdk-arduino-yun#27]
Can I use the Bridge library to acess the digital and analog pins ond the board through REST calls (192.xxx.xxx.xxx/digital/13) ? 

I try to use this while sending msg to AWS and it doesn't work.

**Comment by rpcme** [comment]
Hello Gabriel,

Just to clarify:  you have a sketch that composes both bridge server code and AWS IoT SDK code, and when running a code block that sends a message to AWS IoT the send doesn't happen?

**Comment by rpcme** [comment]
Please see https://github.com/aws/aws-iot-device-sdk-arduino-yun/issues/23#issuecomment-251461174

**Comment by GabrielFiletti** [comment]
Yes, that's exactly what is happening. I now understand why . Thanks !
