### ISSUE TITLE
question: upload AWS-IoT-Python-Runtime/ folder to /root

### ISSUE THREAD

**Issue by eczajk1** [aws/aws-iot-device-sdk-arduino-yun#29]
Dumb question, but under [windows installation](https://github.com/aws/aws-iot-device-sdk-arduino-yun#installation-on-windows), item 5, where it says...

> Start WinSCP and upload AWS-IoT-Python-Runtime/ folder to /root on the board.

does that mean to upload the entire folder or just the contents?

**Comment by liuszeng** [comment]
Hi @eczajk1 ,

Thank you very much for your interest in AWS IoT Arduino Yun SDK!

You should copy the entire folder `AWS-IoT-Python-Runtime/` to `/root` on the Yun board. It is the path used to start the Python runtime from ATmega32u4 from the sketch. See the following line:
https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Arduino-Yun-Library/aws_iot_mqtt.cpp#L37

Thanks,
Liusu
