### ISSUE TITLE
ThingShadowEcho example problems

### ISSUE THREAD

**Issue by eczajk1** [aws/aws-iot-device-sdk-arduino-yun#34]
Trying to adapt the "ThingShadow" example, but I keep getting these errors:

```shell
AWS IoT SDK Version(dev) 2.2.0-

root@Seeed:~/AWS-IoT-Python-Runtime/runtime# 
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
/bin/ash: 1: not found
/bin/ash: /root: Permission denied
Linux
/
```

Later (I think when I expect the sketch to get shadow), I get this:

```shell
Exception in thread Thread-4 (most likely raised during interpr
Yield failed.
/bin/ash: 1: not found
/bin/ash: z: not found
Yield failed.
```

How best to diagnose these?

**Comment by liuszeng** [comment]
Hi @eczajk1 ,

You can manually turn on the logging and write the logs into a file on embedded Linux. You will need to add the following lines after [this line](https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Python-Runtime/runtime/runtimeHub.py#L102):

    logging.basicConfig(filename=srcLogDirectory + "yunPy.log", level=logging.DEBUG)

Note that the Python runtime package has a dedicated directory for logs: `AWS-IoT-Python-Runtime/log/`, which is the default value configured as `srcLogDirectory`. Once configured, you should be able to see log files in that directory for debugging purpose.

Also note that, without an SD card, logging to a file will be consuming Yun's on-board memory, which has a limited number of writes. Be aware of the file writes you are about to perform when you enable the logging.

Hope the above helps.

Thanks,
Liusu

**Comment by eczajk1** [comment]
Thanks.  This helps.

I'll close as I think my error is related to something I introduced.
