### ISSUE TITLE
Last Will and Testament (LWT)

### ISSUE THREAD

**Issue by eczajk1** [aws/aws-iot-device-sdk-arduino-yun#38]
Question: Are there plans to incorporate the ability to include a Last Will and Testament at the connect stage?  Or is there already a way to do this?

See "Detecting a Thing is Connected", here:
http://docs.aws.amazon.com/iot/latest/developerguide/thing-shadow-data-flow.html

**Comment by vareddy-zz** [comment]
Hi @eczajk1 ,
Thank you for your interest in AWS IoT!
The Python code that runs on the Arduino Yun's Linux processor is based on the AWS IoT Python SDK and does support the ability to add the LWT to the connect packet. But currently we do not have an Arduino API which makes use of that. 
We do have plans to add it into the API but we will not be able to give a concrete estimate on when that is going to be merged in.
Please let us know if you have any more questions about the SDK.
Varun
