### ISSUE TITLE
Adruino yun sdk setup issue

### ISSUE THREAD

**Issue by karanamsridhar** [aws/aws-iot-device-sdk-arduino-yun#4]
Hello, recently i got an arduino yun and downloaded aws arduino yun sdk and followed the installation steps on windows environment. I am getting setup failed, config failed, connect failed messages when trying to start the basic pub sub example, instead of serial monitor i am using console for printing information. I have verified that my yun is on the same network as my computer and tried couple of other small non aws programs which seems to be working alright. The CA root certificate, private key and certificate which i got from AWS console, which i am using with yun, if i use the same with Raspberry pi, its working correctly with the c sdk. Any pointers on what else i can check for the setup to work on yun would be a great help.

**Comment by liuszeng** [comment]
Hi @karanamsridhar 

Thank you for trying out AWS IoT Arduino Yun SDK. One thing that you can check is that the python script and the certs folder are put into the correct path on openWRT:

/root/
--aws_iot_mqtt_client.py
--/certs/
----CAfile
----privatekey
----certificate

Could you please provide the error code you are having with this issue? That will be really helpful.

Thanks,
AWS IoT Device SDK Team

**Comment by karanamsridhar** [comment]
Hi @liuszeng, thanks for the reply, i checked for the above files and they were in the correct location. After i looked at the aws_iot_mqtt.cpp in the arduino library, i noticed that the setup method was using serial communication, earlier i was uploading the sketch to yun over wifi and was using bridge and console to print the output, since i was having some problem with serial communication setup, but after i read some more on how to setup serial communication, i was able to upload the sketch over com port and then the application worked correctly.

**Comment by abhirocks550** [comment]
Hello i tried steps mentioned but on serial monitor i see following output 

AWS IoT SDK Version(dev) 2.1.0-
Connect failed!
-13
or 
Setup failed!
-5

from where can i get root-CA.crt ?

i checked in openWRT this has /root/AWS-IoT-Python-Runtime folder also certs folder is located at /root/AWS-IoT-Python-Runtime/certs/  so i changed  this line in aws_iot_config.h 
#define AWS_IOT_PATH_PREFIX "/root/AWS-IoT-Python-Runtime/certs/".

can someone please help?

**Comment by abhirocks550** [comment]
There were some issues in sketch. Problem has been solved.

following video tutorial helped me
https://www.youtube.com/watch?v=kpVvfvsBcx4#t=43.117052
