### ISSUE TITLE
setup Failed with error -5

### ISSUE THREAD

**Issue by satay99** [aws/aws-iot-device-sdk-arduino-yun#43]
Just installed the sdk in arduino yun and got this setup failed! message from the Serial monitor as below :-

Setup failed!
-5

What is -5 and what is the possible cause ? I am using arduino 1.6.12 IDE. Any help will be appreciated.

**Comment by hedeshianaws** [comment]
Hello, thank your for your interest in the AWS IoT Arduino Yun SDK. 

Error codes can be found here: AWS-IoT-Arduino-Yun-Library/aws_iot_error.h
In your case, -5 means SERIAL1_COMMUNICATION_ERROR. Essentially, the AVR is unable to communicate with the AR9331 in the Yun. You may want to take a look at aws_iot_mqtt_client::find_baud_type()  in aws_iot_mqtt.cpp line 41 (https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Arduino-Yun-Library/aws_iot_mqtt.cpp#L41) to see if you may be hitting one of the conditions which may cause the serial connection to fail.

**Comment by liuszeng** [comment]
Hi @satay99 ,

We have not heard from you for a while. We are closing the issue for now. If you have any further questions, please feel free to re-open this issue or start a new thread.

Thanks,
Liusu
