### ISSUE TITLE
Beyond AWS IoT?

### ISSUE THREAD

**Issue by LabGrunt** [aws/aws-iot-device-sdk-arduino-yun#52]
I'm looking for tutorial suggestions for the next steps, like

- How to store data from Arduino Yun to DynamoDB or any other database.
- Is Lambda or Kinesis necessary and how configure them with Yun? What applications would need these two services?

**Comment by liuszeng** [comment]
Hi @LabGrunt ,

Thank you very much for your interest in AWS IoT Arduino Yun SDK.

AWS IoT has a module called Rules engine that helps you set up corresponding backend service that processes MQTT messages published to dedicated topics. This will help you to use the data contained in your MQTT messages in other AWS services you want. More details can be found in the following documentation:
http://docs.aws.amazon.com/iot/latest/developerguide/iot-rules-tutorial.html

Hope this helps.

Thanks,
Liusu

**Comment by vareddy-zz** [comment]
HI @LabGrunt,
We haven't heard from you in over a week so we are closing this issue. Please feel free to open a new issue if you have any questions about the Arduino SDK. 
Thanks!
Varun
