### ISSUE TITLE
Connect Failed! (-1) issue using BasicPubSub

### ISSUE THREAD

**Issue by ciaowecia81** [aws/aws-iot-device-sdk-arduino-yun#54]
Hello, I am trying to connect my YUN (with OpenWrt) to AWS IoT using this SDK. I have followed every step carefully, when I try using BasicPubSub Example .
When teh sketch runs I receive a response "Connect failed" with code "-1".
I read the issue #28, but my problem is not solved.
I use the Windows platform to update the YUn system.
Thanks

**Comment by hedeshianaws** [comment]
Thank you for your interest in AWS IoT. Can you elaborate on what steps from issue #28 you've tried and what the results were?

**Comment by ciaowecia81** [comment]
Hi,
I add the row
Serial.println(rw_buf);
in the file aws_iot_mqtt.cpp#L851
to investigate the problem,  but the arduino monitor doesn't write anything.
Can you help me abiut this ?
Thanks

**Comment by liuszeng** [comment]
Hi @ciaowecia81 ,

Thank you very much for using AWS IoT Arduino Yun SDK.

To further debug the issue, can you confirm that you have installed AWSIoTPythonSDK v1.0.0 on your OpenWRT during the installation steps for Yun SDK? To check that, you can use the following command:
```
pip show AWSIoTPythonSDK
```

You should be able to see the following output:
```
Name: AWSIoTPythonSDK
Version: 1.0.0
Summary: SDK for connecting to AWS IoT using Python.
Home-page: https://github.com/aws/aws-iot-device-sdk-python.git
Author: Amazon Web Service
Author-email: UNKNOWN
License: UNKNOWN
Location: /Library/Python/2.7/site-packages
Requires: 
```

Thanks,
Liusu

**Comment by ciaowecia81** [comment]
Hi Liusu,
yes I able to see what you write

Name: AWSIoTPythonSDK
Version: 1.0.0
Summary: SDK for connecting to AWS IoT using Python.
Home-page: https://github.com/aws/aws-iot-device-sdk-python.git
Author: Amazon Web Service
Author-email: UNKNOWN
License: UNKNOWN
Location: /Library/Python/2.7/site-packages
Requires:

**Comment by liuszeng** [comment]
Hi @ciaowecia81 ,

Thank you very much for providing the information.

Can you try to clone down the examples for Python SDK v1.0.0 from the following link onto the OpenWRT?
https://github.com/aws/aws-iot-device-sdk-python/tree/v1.0.0

After that, can you try to run the Python SDK sample using the same credentials you use in Yun SDK and see if there is any issue?

Thanks,
Liusu

**Comment by vareddy-zz** [comment]
Hi @ciaowecia81 ,
We haven't heard back from you in a long time so we are closing this issue. Please create a new issue if you have any questions about the Arduino SDK.
Thanks!
Varun
