### ISSUE TITLE
Disconnected from AWS  if the shadow update exceeds 10 seconds

### ISSUE THREAD

**Issue by LabGrunt** [aws/aws-iot-device-sdk-arduino-yun#66]
I've been playing around with the ThermostatSimulatorDevice. 

I noticed that when I increased the delay value in the loop function above 10 seconds, the Yun was disconnected. I wanted to increase the interval between the shadow updates to a longer time or do shadow update when a button is pressed. 

I also noticed that after the connection is successful, the first shadow update must happen within 13 seconds. 

Is there any way to change the time interval?

I tried changing two things:
1. Set myClient.connect(new_interval), where new_interval = 60 or 120. 
2. Change CMD_TIME_OUT in aws_iot_config_SDK.h

But those two changes did not have any effects on the disconnection timing. 

Thanks.

**Comment by gordonwang0** [comment]
Hi @LabGrunt,

Please take a look at #49.  I think this is the same problem.

**Comment by gordonwang0** [comment]
Hi @LabGrunt,

Let me know if you need any more help on this.  Closing issue.
