### ISSUE TITLE
SSL Connect Error 

### ISSUE THREAD

**Issue by ayyoob** [aws/aws-iot-device-sdk-arduino-yun#68]
Hi,

I am trying to execute the BasicPubSub example in an Arduino Yun, I ended up with an error connection failed with the error code -10. Its working fine when I use the certs using a desktop MQTT.fx client or when using the AWS IoT Python SDK. However, I am struggling to connect it with the Arduino Yun. Any thoughts on possible reason where this can go wrong ?.

Thanks,

**Comment by gordonwang0** [comment]
Hi @ayyoob,

This error generally happens because of an incorrect endpoint.  Please see:
- #67 
- #46 
- #41 
- #22

**Comment by gordonwang0** [comment]
Hi @ayyoob,

Please let me know if you need any more help with this.  Closing issue.
