### ISSUE TITLE
Problem with Demos

### ISSUE THREAD

**Issue by jjferreira** [aws/aws-iot-device-sdk-arduino-yun#8]
Good evening im having problems when running the Sample bits of code.

Im using and Arduino yun, and I keep getting

---

AWS IoT SDK Version(dev) 1.0.3-

Connect failed!
## -13

When trying to run BasicPubSub.

Pls advise

**Comment by liuszeng** [comment]
Hi @jjferreira 

Thank you very much for using AWS IoT Arduino Yun SDK!

The [error code](https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/README.md#errorcode) -13 indicates that the SDK is not able to find the credentials specified in your aws_iot_config.h file on Linux side of Arduino Yun board. You can check the following things: 

A. Verify that you have correctly configured the root CA, certificate and private key file name in aws_iot_config.h in the sample.

```
...
#define AWS_IOT_ROOT_CA_FILENAME "<YOUR ROOT CA FILE>"           // your root-CA filename
#define AWS_IOT_CERTIFICATE_FILENAME "<YOUR CERTIFICATE>"        // your certificate filename
#define AWS_IOT_PRIVATE_KEY_FILENAME "<YOUR PRIVATE KEY>"        // your private key filename
...
```

B. Verify that you have upload the credentials into the right directory on the Linux side of Arduino Yun board. This is done during the [installation step](https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/README.md#installation), step 4 and 5 for both Linux/MacOS and Windows installation. You can ssh into the Linux side and do the check. You may need to do a power cycle to make changes valid if you made any file changes on the Linux side.

Thanks,
Liusu

**Comment by jjferreira** [comment]
You were spot on, I had a problem with the naming convention on "<YOUR ROOT
CA FILE>" .

I can see data now :) tks

**Comment by jjferreira** [comment]
Good evening Liusu.

Last night the example was working, so I turned my machine off and then on
today.

Whoever I'm getting , I dint change anything since yesterday.

What do you think it its.

Cheers

Jack

PUBLISH_GENERIC_ERROR = -17,

AWS IoT SDK Version(dev) 1.0.3-

loop 0 done
Publish failed!
-17
loop 1 done
loop 2 done
loop 3 done
Publish failed!
-17
loop 4 done
loop 5 done
loop 6 done
loop 7 done
Publish failed!
-17
loop 8 done
loop 9 done
loop 10 done
Publish failed!
-17
loop 11 done
loop 12 done
loop 13 done
loop 14 done
loop 15 done
loop 16 done
loop 17 done
Publish failed!
-17
loop 18 done
loop 19 done
loop 20 done
Publish failed!
-17
loop 21 done
loop 22 done
loop 23 done
Publish failed!
-17
loop 24 done
loop 25 done
loop 26 done
Publish failed!
-17
loop 27 done
loop 28 done
Publish failed!
-17
loop 29 done
loop 30 done
loop 31 done
Publish failed!
-17
loop 32 done
loop 33 done
loop 34 done
Publish failed!
-17
loop 35 done
loop 36 done
loop 37 done
Publish failed!
-17
loop 38 done
loop 39 done
loop 40 done
Publish failed!
-17
loop 41 done
loop 42 done
loop 43 done
Publish failed!
-17
loop 44 done
loop 45 done
Publish failed!
-17
loop 46 done
loop 47 done
loop 48 done
Publish failed!
-17
loop 49 done
loop 50 done
loop 51 done
Publish failed!
-17
loop 52 done
loop 53 done
Publish failed!
-17
loop 54 done
loop 55 done
Publish failed!
-17
loop 56 done
loop 57 done
Publish failed!
-17
loop 58 done
loop 59 done
loop 60 done
loop 61 done
loop 62 done
loop 63 done
Publish failed!
-17
loop 64 done
loop 65 done
loop 66 done
Publish failed!
-17
loop 67 done
loop 68 done
loop 69 done
loop 70 done
Publish failed!
-17
loop 71 done
loop 72 done
loop 73 done
Publish failed!
-17
loop 74 done
loop 75 done
loop 76 done
Publish failed!
-17
loop 77 done
loop 78 done
loop 79 done
Publish failed!
-17
loop 80 done
loop 81 done
loop 82 done
loop 83 done
Publish failed!
-17
loop 84 done
loop 85 done
Publish failed!
-17
loop 86 done
loop 87 done
Publish failed!
-17
loop 88 done
loop 89 done
loop 90 done
loop 91 done
Publish failed!
-17
loop 92 done
loop 93 done
loop 94 done
Publish failed!
-17
loop 95 done
loop 96 done
loop 97 done
loop 98 done
loop 99 done
loop 100 done
loop 101 done
Publish failed!
-17
loop 102 done
loop 103 done
loop 104 done
loop 105 done
loop 106 done
loop 107 done
loop 108 done
Publish failed!
-17
loop 109 done
loop 110 done
Publish failed!
-17
loop 111 done
loop 112 done
Publish failed!
-17
loop 113 done
loop 114 done
loop 115 done
loop 116 done
loop 117 done
loop 118 done
Publish failed!
-17
loop 119 done
loop 120 done
Publish failed!
-17
loop 121 done
loop 122 done
Publish failed!
-17
loop 123 done
loop 124 done
Publish failed!
-17
loop 125 done
loop 126 done
Publish failed!
-17
loop 127 done
loop 128 done
Publish failed!
-17
loop 129 done
loop 130 done
Publish failed!
-17
loop 131 done
loop 132 done
Publish failed!
-17
loop 133 done
loop 134 done
loop 135 done
loop 136 done
Publish failed!
-17
loop 137 done
loop 138 done
loop 139 done
Publish failed!
-17
loop 140 done
loop 141 done
loop 142 done
loop 143 done
Publish failed!
-17
loop 144 done
loop 145 done
loop 146 done
Publish failed!
-17
loop 147 done
loop 148 done
loop 149 done
loop 150 done
Publish failed!
-17
loop 151 done
loop 152 done
loop 153 done
Publish failed!
-17
loop 154 done
loop 155 done
loop 156 done
loop 157 done
Publish failed!
-17
loop 158 done
loop 159 done
loop 160 done
Publish failed!
-17
loop 161 done
loop 162 done
loop 163 done
loop 164 done
Publish failed!
-17
loop 165 done
loop 166 done
loop 167 done
Publish failed!
-17
loop 168 done
loop 169 done
loop 170 done
loop 171 done
Publish failed!
-17
loop 172 done
loop 173 done
loop 174 done
loop 175 done
loop 176 done
Publish failed!
-17
loop 177 done

**Comment by liuszeng** [comment]
Hi Jack,

Thank you very much for your information.

It seems that the board is no longer subscribed to the topic it publishes to. There might be a network failure in between. Could you please try to do a power-cycle of the Arduino Yun board and upload the sketch again? Please make sure that the Yun board is fully boot up and got internet access before you start the sketch.

Please let us know how it works.

Thanks,
Liusu

**Comment by jgouy** [comment]
Hi there,
     I am trying the ThermostatSimulatorApp.py application but it seems that something is wrong with the JSON definitions. 
I am able to connect to the AWS IOT sucessfully:
Following the serial print from the Arduino monitor:
AWS IoT SDK Version(dev) 1.0.3-

[LOG] command: setup completed.
[LOG] command: config completed.
[LOG] command: connect completed.
[LOG] command: shadow init completed.
[LOG] command: register thing shadow delta function completed.
[LOG] command: shadow update completed.
[LOG] command: shadow update completed.
[LOG] command: shadow update completed.

After this point I started the python application ThermostatSimulatorApp and the graphical interface started ok but all the characters are X's for the reported and desired temperatures. 
At the same time I start the application I start receiving the following message:

Invalid JSON or missing attribute
Invalid JSON or missing attribute
Invalid JSON or missing attribute
Invalid JSON or missing attribute
Invalid JSON or missing attribute

When I try to send a new desired temperature I receive the following message:

Set Temp: 60.0 F
Invalid JSON or missing attribute
Invalid JSON or missing attribute
Invalid JSON or missing attribute
Invalid JSON or missing attribute
Invalid JSON or missing attribute

Can you help me on that? I am a very unexperienced programmer :-)

Thank you very much!

**Comment by liuszeng** [comment]
Hi @jgouy,

Thank you very much for using AWS IoT Arduino Yun SDK!

The Simple Thermostat Simulator Example basically shows you how devices running the SDK interacts with the App using AWS IoT MQTT as communication in between. The error you had indicates that there is a JSON parsing error in the Python App script. You can check the following things:

A. Make sure that the Yun board is updating the shadow name called "room". To check this, you can check the macro `AWS_IOT_MY_THING_NAME` in your configuration file `aws_iot_config.h` along with the example sketch.
B. Make sure that the property that gets updated on the Yun board is "Temp". By default, the example sketch will do this for you in the delta callback:

```
void msg_callback_delta(char* src, int len) {
    String data = String(src);
    int st = data.indexOf("\"state\":") + strlen("\"state\":");
    int ed = data.indexOf(",\"metadata\":");
    String delta = data.substring(st, ed);
    st = delta.indexOf("\"Temp\":") + strlen("\"Temp\":");
    ed = delta.indexOf("}");
    String delta_data = delta.substring(st, ed);
    desiredTemp = delta_data.toFloat();
}
```

C. Check to see what is contained in the payload of the received message payload. To do that, uncomment the `print` line (line 49) in `customCallback` in [`ThermostatSimulatorApp.py`](https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/ExampleAppScript/ThermostatSimulatorApp/ThermostatSimulatorApp.py):

```
def customCallback(client, userdata, message):
    print "ThermostatApp received a new message: " + str(message.payload) + " from topic: " + str(message.topic)
    ...
```

Normally, it should be a JSON file containing reported state and desired state from topic "$aws/things/room/shadow/get/accepted" as default:

```
{
    "state": {
        "desired": {
            "Temp": 60
        },
        "reported": {
            "Temp": 70
        }
    },
    ...
}
```

Please let us know how it goes.

Thanks,
Liusu

**Comment by jgouy** [comment]
Hi Liusu,
              Thanks a lot for your feedback. I’ve checked the AWS_IOT_MY_THING_NAME  and it was not set to “room”, so I changed it and it is working now!

Thank you very much!

Do you have a reference, more detailed, literature for a beginner like me to develop on AWS IoT applications using Python and Arduino Yun?
I’d like something that starts with a simple “Hello World” and grow on complexity and functionality as the chapters evolves.

Very best regards,

**Comment by liuszeng** [comment]
Hi @jgouy,

Glad to know that you got it working.

Currently, we do not have a general reference literature for AWS IoT App development using Python and Arduino Yun. We have SDKs for different programming language withs examples that will give you an overview about how you will work with AWS IoT using your devices: [AWS IoT Embedded C SDK](https://github.com/aws/aws-iot-device-sdk-embedded-C), [AWS IoT Node.js SDK](https://github.com/aws/aws-iot-device-sdk-js) and also the AWS IoT Arduino Yun SDK.

As for AWS IoT Arduino Yun SDK, several examples are available for you to get familiar with AWS IoT. [The Basic PubSub Example](https://github.com/aws/aws-iot-device-sdk-arduino-yun/tree/master/AWS-IoT-Arduino-Yun-Library/examples/BasicPubSub) gives you a brief overview of the MQTT publish/subscribe communication model. [The ThingShadowEcho](https://github.com/aws/aws-iot-device-sdk-arduino-yun/tree/master/AWS-IoT-Arduino-Yun-Library/examples/ThingShadowEcho) gives a brief overview of the shadow concept and how you will use the SDK to interact with AWS IoT. [The ThermostatSimulator](https://github.com/aws/aws-iot-device-sdk-arduino-yun/tree/master/AWS-IoT-Arduino-Yun-Library/examples/ThermostatSimulatorDevice) provides an example of how you can use shadow concept interacting with AWS IoT and create smart devices with control over App.

As for Python development for AWS IoT, the one you see in the Thermostat Simulator Example is actually using the [Python core library](https://github.com/aws/aws-iot-device-sdk-arduino-yun/tree/master/AWS-IoT-Python-Runtime) in AWS IoT Arduino Yun SDK. This example is intended to provide a way for developers to get connected to AWS IoT using Python, MQTT and might not be that straightforward. We are currently working on a Python Device SDK (MQTT) which will make it a lot easier to develop Apps with AWS IoT MQTT communication.

If you are looking for some inspirations and cool ideas, you can check out the [AWS IoT Mega Contest](https://www.hackster.io/challenges/AWSIoTMegaContest). There are a lot of interesting projects using different AWS IoT SDKs together with other AWS services.

Hope this will help.

Thanks,
Liusu

**Comment by jgouy** [comment]
Hi Liusu,
              The potential of AWS IoT is beyond imagination in my opinion. I think that if it’s capabilities were better documented, the adoption would be massive. For IoT solutions, one should understand that the majority, or at least a good portion, of the adopters/programmers will be the Operations guys, engineers professionals that normally are not experienced programmers. I am trying to develop myself so I can teach than but I am not an experienced programmer to.

I am very glad that you are developing the Python Device SDK (MQTT), this is a major part for the fast adoption for these OT professionals including myself.

Thanks a lot for your help and very best regards,

**Comment by abhirocks550** [comment]
/*
- Copyright 2010-2016 Amazon.com, Inc. or its affiliates. All Rights Reserved.
  *
- Licensed under the Apache License, Version 2.0 (the "License").
- You may not use this file except in compliance with the License.
- A copy of the License is located at
  *
-  http://aws.amazon.com/apache2.0
  *
- or in the "license" file accompanying this file. This file is distributed
- on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
- express or implied. See the License for the specific language governing
- permissions and limitations under the License.
  */

#include <aws_iot_mqtt.h>
#include <aws_iot_version.h>
#include "aws_iot_config.h"

aws_iot_mqtt_client myClient; // init iot_mqtt_client
char msg[32]; // read-write buffer
int cnt = 0; // loop counts
int rc = -100; // return value placeholder
bool success_connect = false; // whether it is connected

float temperature = 21.5; 
int   lightValue = 150;
int   moisturValue = 0;

char data[80];

// Basic callback function that prints out the message
void msg_callback(char\* src, unsigned int len, Message_status_t flag) {
  if(flag == STATUS_NORMAL) {
    Serial.println("CALLBACK:");
    int i;
    for(i = 0; i < (int)(len); i++) {
      Serial.print(src[i]);
    }
    Serial.println("");
  }
}

void setup() {
  // Start Serial for print-out and wait until it's ready
  Serial.begin(115200);
  while(!Serial);
  //
  char curr_version[80];
  sprintf(curr_version, "AWS IoT SDK Version(dev) %d.%d.%d-%s\n", VERSION_MAJOR, VERSION_MINOR, VERSION_PATCH, VERSION_TAG);
  Serial.println(curr_version);
  // Set up the client
  if((rc = myClient.setup(AWS_IOT_CLIENT_ID)) == 0) {
    // Load user configuration
    if((rc = myClient.config(AWS_IOT_MQTT_HOST, AWS_IOT_MQTT_PORT, AWS_IOT_ROOT_CA_PATH, AWS_IOT_PRIVATE_KEY_PATH, AWS_IOT_CERTIFICATE_PATH)) == 0) {
      // Use default connect: 60 sec for keepalive
      if((rc = myClient.connect()) == 0) {
        success_connect = true;
        // Subscribe to "topic1"
        if((rc = myClient.subscribe("topic1", 1, msg_callback)) != 0) {
          Serial.println("Subscribe failed!");
          Serial.println(rc);
        }
      }
      else {
        Serial.println("Connect failed!");
        Serial.println(rc);
      }
    }
    else {
      Serial.println("Config failed!");
      Serial.println(rc);
    }
  }
  else {
    Serial.println("Setup failed!");
    Serial.println(rc);
  }
  // Delay to make sure SUBACK is received, delay time could vary according to the server
  delay(2000);
}

void loop() {

 //Creating the JSON payload  
 String temp = "\"temp\": " + String(temperature) ;
 String light = ", \"lightval\":" + String(lightValue) ;
 String soilMoist = ", \"moistval\":" + String(moisturValue) ;
 // Add both value together to send as one string. 
 String value = temp + light +soilMoist;
 Serial.println(value);
 String payload = "{" + value + "}";
 payload.toCharArray(data, (payload.length() + 1));

Serial.println(data);

  if(success_connect) {
    // Generate a new message in each loop and publish to "topic1"
    sprintf(msg, "new message %d", cnt);

```
if((rc = myClient.publish("topic/plantdata", data, strlen(data), 1, false)) != 0) {
  Serial.println("Publish failed!");
  Serial.println(rc);
}

// Get a chance to run a callback
if((rc = myClient.yield()) != 0) {
  Serial.println("Yield failed!");
  Serial.println(rc);
}

// Done with the current loop
sprintf(msg, "loop %d done", cnt++);
Serial.println(msg);

delay(10000);
```

  }
}

above is my sketch i am getting error 

Publish failed!
-1

could someone please help ?

One more thing is that what is right way to pass JSON in publish method ?

**Comment by liuszeng** [comment]
Hi @abhirocks550 ,

Thank you very much for using AWS IoT Arduino Yun SDK!

Error code -1, which is GENERIC_ERROR, is usually caused by a broken message transmitted from the Python runtime on AR9331. Such error might be caused by an unexpected error on Python runtime, or a serial1 communication issue. Could you please verify the following:
0. Which version of the SDK are you using? Can you provide a serial monitor printout?
1. Are you still able to run the BasicPubSub example provided in the SDK package correctly?
2. Are you seeing this error in publish each time you run the sketch? Can you confirm that you are connected to the service?
3. Do you see a warning message when compiling the sketch: "Low memory available, stability problems may occur."?
4. In [aws_iot_mqtt.cpp](https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Arduino-Yun-Library/aws_iot_mqtt.cpp), line 838, could you please add a line to printout the `rw_buf` and check what is the returned message from Python runtime when the publish failure happens?

```
rw_buf[ptr] = '\0'; // add terminator in case of garbage data in rw_buf
Serial.println(rw_buf); // ***Newly added
```

As for JSON construction, it should be good for what you have in your sketch. For other references, you can check another example in the SDK: [Thermostat simulator](https://github.com/aws/aws-iot-device-sdk-arduino-yun/blob/master/AWS-IoT-Arduino-Yun-Library/examples/ThermostatSimulatorDevice/ThermostatSimulatorDevice.ino). This example contains the piece of code to construct a JSON payload and uses shadow (basically MQTT publishes) to interact with AWS IoT.

Please let us know how it goes. Please also feel free to open another thread if necessary.

Thanks,
Liusu
